### PR TITLE
Export a bunch of interfaces to allow external font rendering

### PR DESCRIPTION
**Pull request by rhelmot**
As foretold in #134. This is essentially the smallest possible refactor I could make in order to externally manage font atlases and push them into femtovg.

If for any reason this is an unsavory change, let me know and I will do my best to make it more palatable.

[Sample usage](https://github.com/vizia/vizia/blob/8359c4dfe0234ba53ed245a42612e9e0967d46c4/crates/vizia_core/src/text/cosmic.rs#L124), now merged into Vizia's main branch.

### CODE REVIEW

**Comment by tronical** [comment]
Interesting approach! Do I understand correctly that this basically also delegates the glyph atlas texture handling to the caller?

**Review by tronical — APPROVED** [review]
Thanks for the explanation. I quite like this :). It's really minimal and also only exposes the texture format. I think what would really help is documentation (about the expected format of the texture, the coordinate system etc).

Given that nobody else commented I suppose there are no other objections:). Want me to merge as-is?

**Comment by rhelmot** [comment]
I added an example which should hopefully illustrate the bits you were interested in.

The example panics if you resize the window too small, but this is a bug in cosmic-text.

**Comment by rhelmot** [comment]
Oh, if you were directing that question at me: yes, you can merge this as-is.

**Comment by tronical** [comment]
Looks like there’s a build issue in cosmic-text. Is that MSRV related?

**Comment by rhelmot** [comment]
Testing indicates cosmic-text has an undeclared MSRV of 1.63, but for the life of me I don't understand what the problem is and what from the 1.63 changelogs is fixing it. So we have a few options:

- Bump femtovg MSRV to 1.63
- Help me figure out how to fix cosmic-text for 1.61
- Move the example to a pending pull request which will be merged when one of the above is satisfied

**Comment by tronical** [comment]
I bumped the MSRV to 1.63 in femtovg master branch. Can you rebase your PR?

**Pull request merged**
