### PR TITLE
Make it possible to run the demo in the browser

### PR DESCRIPTION
**Pull request by tronical**
* canvas glue code in demo.rs takes care of fetching the canvas element.
* From the image crate we don't need the jpeg-rayon variant but the
  regular one, as rayon uses threads, which don't work out of the box
  in Rust's wasm32-unknown-unknown target.
* Assets like fonts and images are embedded into the binary
* The usvg crate has text disabled, because that would pull a bunch
  of dependencies that can't be cross-compiled.
* Use the instant crate to get a wasm working version of the
  performance counter.

### CODE REVIEW

**Comment by adamnemecek** [comment]
Is there a reason why you are using winit 0.22 instead of 0.24? 0.22 doesn't run on Apple M1 laptops.

**Comment by tronical** [comment]
It’s the one that the glutin version used depends on. I’d be happy to bump glutin and winit to a current version but that requires further minor unrelated changes due to API breakage. Would you prefer that to go into this MR or separate?

**Comment by adamnemecek** [comment]
I think I would prefer it in this PR if that's not too much of a hassle.

**Comment by tronical** [comment]
No problem at all, I’ll include it tomorrow.

**Comment by tronical** [comment]
Fixed a typo in the resource deps, moved the jpeg dependency to dev-dependencies (the core crate shouldn't depend on a specific image format) and clarified the README a little.

**Pull request merged**
